apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ecommerce
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: s4357333@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: nginx
