apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productDb.serviceName }}
  labels:
    app: {{ .Values.productDb.name }}
spec:
  selector:
    app: {{ .Values.productDb.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.productDb.port }}
      targetPort: {{ .Values.productDb.port }}
  type: ClusterIP
