apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.serviceName }}
  labels:
    app: {{ .Values.rabbitmq.name }}
spec:
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
