apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.serviceName }}
  labels:
    app: {{ .Values.auth.name }}
spec:
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.auth.servicePort }}
      targetPort: {{ .Values.auth.port }}
  type: ClusterIP
