apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.product.serviceName }}
  labels:
    app: {{ .Values.product.name }}
spec:
  selector:
    app: {{ .Values.product.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.product.servicePort }}
      targetPort: {{ .Values.product.port }}
  type: ClusterIP
