apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.order.serviceName }}
  labels:
    app: {{ .Values.order.name }}
spec:
  selector:
    app: {{ .Values.order.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.order.servicePort }}
      targetPort: {{ .Values.order.port }}
  type: ClusterIP
